version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: node-app
    command: npm run nodemon
    env_file:
      - ./.env
    environment:
      - MIN_MOVIE_COUNT=${MIN_MOVIE_COUNT}
      - MAX_MOVIE_COUNT=${MAX_MOVIE_COUNT}