version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: node-app
    command: npm run nodemon
    env_file:
      - ./.env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}